### ISSUE TITLE
Home Services Component

### ISSUE THREAD

**Issue by rfairooz** [acm-ucr/winc-website#34]
<img width="537" alt="Screenshot 2023-10-13 at 11 30 01 AM" src="https://github.com/acm-ucr/winc-website/assets/91511317/55da6980-8db0-4715-9ae7-f85f8378073c">
Make your file Grow.js under arc/components/home and finish this whole component. Import the home service card component and button component

**Comment by roshinira123** [comment]
![image](https://github.com/acm-ucr/winc-website/assets/53918739/1a029332-01da-43b5-b2c2-bfef69690ba8)
Finished Growth component
